//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.ElementsCPS.Apps.WebUI.MasterPages {
    
    
    public partial class DefaultPortalMaster {
        
        /// <summary>
        /// PageHead control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder PageHead;
        
        /// <summary>
        /// hpHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalHeader hpHeader;
        
        /// <summary>
        /// hpMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalMenu hpMenu;
        
        /// <summary>
        /// hpMenuItem_Home control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalMenuItem hpMenuItem_Home;
        
        /// <summary>
        /// hpMenuItem_MyInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalMenuItem hpMenuItem_MyInfo;
        
        /// <summary>
        /// hpMenuItem_Redirect control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalMenuItem hpMenuItem_Redirect;
        
        /// <summary>
        /// hpMenuItem_ConfigurationService control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalMenuItem hpMenuItem_ConfigurationService;
        
        /// <summary>
        /// hpMenuItem_Jumpstation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalMenuItem hpMenuItem_Jumpstation;
        
        /// <summary>
        /// hpMenuItem_Admin_DataAdmin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalMenuItem hpMenuItem_Admin_DataAdmin;
        
        /// <summary>
        /// hpMenuItem_Admin_UserAdmin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalMenuItem hpMenuItem_Admin_UserAdmin;
        
        /// <summary>
        /// hpMenuItem_Admin_SystemAdmin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalMenuItem hpMenuItem_Admin_SystemAdmin;
        
        /// <summary>
        /// PortalNavigationTreeArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder PortalNavigationTreeArea;
        
        /// <summary>
        /// ajaxPartialPostBackSynchronizer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Encosia.PostBackRitalin ajaxPartialPostBackSynchronizer;
        
        /// <summary>
        /// ajaxContentAreaUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ajaxContentAreaUpdatePanel;
        
        /// <summary>
        /// lblPageContentAreaTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPageContentAreaTitle;
        
        /// <summary>
        /// PageContentArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder PageContentArea;
        
        /// <summary>
        /// ajaxUpdatePanelAnimationExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.UpdatePanelAnimationExtender ajaxUpdatePanelAnimationExtender;
        
        /// <summary>
        /// txtCalendarExtenderHack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCalendarExtenderHack;
        
        /// <summary>
        /// ajaxCalendarExtenderHack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CalendarExtender ajaxCalendarExtenderHack;
        
        /// <summary>
        /// hpFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HP.HPFx.Web.UI.Portal.PortalFooter hpFooter;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new HP.ElementsCPS.Apps.WebUI.MasterPages.SiteMaster Master {
            get {
                return ((HP.ElementsCPS.Apps.WebUI.MasterPages.SiteMaster)(base.Master));
            }
        }
    }
}
