//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.ElementsCPS.Apps.WebUI.MasterPages {
    
    
    public partial class DefaultOverlayMaster {
        
        /// <summary>
        /// ajaxPartialPostBackSynchronizer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Encosia.PostBackRitalin ajaxPartialPostBackSynchronizer;
        
        /// <summary>
        /// ajaxContentAreaUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ajaxContentAreaUpdatePanel;
        
        /// <summary>
        /// lblPageContentAreaTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPageContentAreaTitle;
        
        /// <summary>
        /// PageContentArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder PageContentArea;
        
        /// <summary>
        /// ajaxUpdatePanelAnimationExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.UpdatePanelAnimationExtender ajaxUpdatePanelAnimationExtender;
        
        /// <summary>
        /// txtCalendarExtenderHack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCalendarExtenderHack;
        
        /// <summary>
        /// ajaxCalendarExtenderHack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CalendarExtender ajaxCalendarExtenderHack;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new HP.ElementsCPS.Apps.WebUI.MasterPages.SiteMaster Master {
            get {
                return ((HP.ElementsCPS.Apps.WebUI.MasterPages.SiteMaster)(base.Master));
            }
        }
    }
}
