-- =============================================
-- Author:	Justin Webster
-- Create date:	2010/06/28
-- Description:	Loads (i.e. inserts) the minimum set of data that is required to test the system's DAL's "Fetch" methods.
-- Note:	Adapted from a script generated by Red Gate SQL Compare.
-- Warning:	This script (as currently implemented) may reseed Identity columns in tables that are not otherwise modified by the script.
-- =============================================

SET NUMERIC_ROUNDABORT OFF
GO
SET XACT_ABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO

BEGIN TRY
	BEGIN TRANSACTION

	PRINT 'Loading "Fetch Method Test" DB data'

	DECLARE @strNewLine VARCHAR(2);
	DECLARE @dtDefaultValue_CreatedOn DATETIME;
	DECLARE @dtDefaultValue_ModifiedOn DATETIME;
	DECLARE @strDefaultValue_CreatedBy NVARCHAR(50);
	DECLARE @strDefaultValue_ModifiedBy NVARCHAR(50);
	DECLARE @intRowStatus_Active int;
	DECLARE @intRowStatus_Inactive int;
	DECLARE @intRowStatus_Deleted int;
	DECLARE @intRole_Administrator int;
	DECLARE @intRole_AccountLocked int;
	DECLARE @intRole_RestrictedAccess int;
	DECLARE @intRole_Everyone int;
	DECLARE @intRole_DataAdmin int;
	DECLARE @intRole_UserAdmin int;
	DECLARE @intRole_TechSupport int;
	DECLARE @intRole_ProjectAdmin int;
	DECLARE @intRole_ProjectRequestor int;
	DECLARE @intRole_Manufacturing int;
	DECLARE @intRole_EnableOptionalFeatures int;
	DECLARE @intRole_ProjectViewer int;
	DECLARE @intRole_ProjectParticipant int;
	DECLARE @intRole_ProjectOwner int;
	DECLARE @CustomerId INT;
	DECLARE @regionLocale int;
	DECLARE @intPilotType_PilotShip int;
	DECLARE @intPilotType_PilotNoShip int;
	DECLARE @intPilotType_NoPilot int;
	DECLARE @intPilotType_VirtualValidation int;

	SET @strNewLine = Char(13) + Char(10);
	SET @dtDefaultValue_CreatedOn = CONVERT(DATETIME, '20090101', 112);
	SET @dtDefaultValue_ModifiedOn = @dtDefaultValue_CreatedOn;
	SET @strDefaultValue_CreatedBy = N'system\system';
	SET @strDefaultValue_ModifiedBy = @strDefaultValue_CreatedBy;
	SET @intRowStatus_Active = 1;
	SET @intRowStatus_Inactive = 2;
	SET @intRowStatus_Deleted = 3;
	SET @intRole_Administrator = 1;
	SET @intRole_AccountLocked = 2;
	SET @intRole_RestrictedAccess = 3;
	SET @intRole_Everyone = 4;
	SET @intRole_DataAdmin = 5;
	SET @intRole_UserAdmin = 6;
	SET @intRole_TechSupport = 7;
	SET @intRole_ProjectAdmin = 8;
	SET @intRole_ProjectRequestor = 9;
	SET @intRole_Manufacturing = 10;
	SET @intRole_EnableOptionalFeatures = 11;
	SET @intRole_ProjectViewer = 12;
	SET @intRole_ProjectParticipant = 13;
	SET @intRole_ProjectOwner = 14;
	SET @intPilotType_PilotShip = 1;
	SET @intPilotType_PilotNoShip = 2;
	SET @intPilotType_NoPilot = 3;
	SET @intPilotType_VirtualValidation = 4;


	PRINT 'Adding rows to [dbo].[Person]'
	BEGIN
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'americas\activeperson', N'Active', Null, N'Person', N'person.active@hp.com', 'system\Administrator', '03-JAN-2009', 'americas\lasta','04-JAN-2009', @intRowStatus_Active,'CommentOfA')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'americas\inactiveperson', N'Inactive', NULL, N'Person', N'person.inactive@hp.com', 'americas\lasta', '02-JAN-2009', 'americas\mukaimur','02-JAN-2009', @intRowStatus_Inactive,'CommentOfB')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'americas\deletedperson', N'Deleted', NULL, N'Person', N'person.deleted@hp.com', 'americas\mukaimur', '01-JAN-2009', 'system\DataAdmin','01-JAN-2009', @intRowStatus_Deleted,'CommentOfC')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'americas\lasta', N'firsta', Null, N'lasta', N'firsta.lasta@hp.com', 'system\DataAdmin', '05-JAN-2009', 'system\Administrator','03-JAN-2009', @intRowStatus_Active,'CommentOfD')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'americas\lastb', N'firstb', NULL, N'lastb', N'firstb.lastb@hp.com', 'system\Administrator', '04-JAN-2009', 'system\UserAdmin','05-JAN-2009', @intRowStatus_Inactive,'CommentOfE')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'americas\lastc', N'firstc', NULL, N'lastc', N'firstc.lastc@hp.com', 'system\UserAdmin', '04-JAN-2009', 'system\Manufacturing','02-JAN-2009', @intRowStatus_Deleted,'CommentOfF')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\Administrator', N'Administrator', Null, N'Role', N'person.Administrator@hp.com', 'system\Manufacturing', '02-JAN-2009', 'system\AccountLocked','04-JAN-2009', @intRowStatus_Active,'CommentOfG')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\DataAdmin', N'DataAdmin', Null, N'Role', N'person.DataAdmin@hp.com', 'system\AccountLocked', '01-JAN-2009', 'americas\mukaimur','03-JAN-2009', @intRowStatus_Active,'CommentOfH')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\UserAdmin', N'UserAdmin', Null, N'Role', N'person.UserAdmin@hp.com', 'system\AccountLocked', '07-JAN-2009', 'system\DataAdmin','06-JAN-2009', @intRowStatus_Active,'CommentOfI')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\ProjectManager', N'ProjectManager', Null, N'Role', N'person.ProjectManager@hp.com', 'americas\mukaimur', '06-JAN-2009', 'americas\mukaimur','07-JAN-2009', @intRowStatus_Active,'CommentOfJ')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\ProjectRequestor', N'ProjectRequestor', Null, N'Role', N'person.ProjectRequestor@hp.com', 'system\DataAdmin', '08-JAN-2009', 'ModifyF','08-JAN-2009', @intRowStatus_Active,'CommentOfK')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\RestrictedAccess', N'RestrictedAccess', Null, N'Role', N'person.RestrictedAccess@hp.com', 'americas\mukaimur', '09-JAN-2009', 'system\Administrator','06-JAN-2009', @intRowStatus_Active,'CommentOfL')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\Everyone', N'Everyone', Null, N'Role', N'person.Everyone@hp.com', 'system\Administrator', '08-JAN-2009', 'system\UserAdmin','07-JAN-2009', @intRowStatus_Active,'CommentOfM')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\AccountLocked', N'LockedOut', Null, N'Role', N'person.AccountLocked@hp.com','system\UserAdmin', '10-JAN-2009', 'system\AccountLocked','08-JAN-2009', @intRowStatus_Active,'CommentOfN')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'americas\lastd', N'firstd', Null, N'lastd', N'firstd.lastd@hp.com', 'system\AccountLocked', '06-JAN-2009', 'system\Manufacturing','09-JAN-2009', @intRowStatus_Active,'CommentOfO')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'americas\laste', N'firste', NULL, N'laste', N'firste.laste@hp.com', 'americas\mukaimur', '10-JAN-2009', 'system\Administrator','10-JAN-2009', @intRowStatus_Inactive,'CommentOfP')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\TechnicalSupport', N'TechnicalSupport', Null, N'Role', N'person.TechnicalSupport@hp.com','system\Manufacturing', '11-JAN-2009', 'system\DataAdmin','15-JAN-2009', @intRowStatus_Active,'CommentOfQ')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\Manufacturing', N'Manufacturing', Null, N'Role', N'person.Manufacturing@hp.com', 'system\AccountLocked', '10-JAN-2009', 'system\Manufacturing','13-JAN-2009', @intRowStatus_Active,'CommentOfR')
		INSERT INTO [dbo].[Person] ([WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId],[Comment]) VALUES (N'system\EnableOptionalFeatures', N'EnableOptionalFeatures', Null, N'Role', N'person.EnableOptionalFeatures@hp.com', 'americas\lasta', '14-JAN-2009', 'system\Administrator','12-JAN-2009', @intRowStatus_Active,'CommentOfS')
	END

	PRINT 'Adding rows to [dbo].[Person_Role]'
	BEGIN
		DECLARE @personId INT;
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'americas\activeperson'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_Administrator, 'system\Administrator', getdate(), 'americas\lasta', getdate(),'CommentOfA')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'americas\inactiveperson'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_ProjectRequestor, 'americas\lasta', getdate(), 'americas\mukaimur', getdate(),'CommentOfB')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'americas\deletedperson'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_Manufacturing, 'americas\mukaimur', getdate(), 'system\Administrator', getdate(),'CommentOfC')

		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\Administrator'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_Administrator, 'system\DataAdmin', getdate(), 'system\UserAdmin', getdate(),'CommentOfD')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\DataAdmin'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_DataAdmin, 'system\Administrator', getdate(), 'system\Manufacturing', getdate(),'CommentOfE')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\UserAdmin'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_UserAdmin,'system\UserAdmin', getdate(), 'system\Everyone', getdate(),'CommentOfF')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\ProjectManager'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_ProjectAdmin, 'system\Manufacturing', getdate(), 'system\DataAdmin', getdate(),'CommentOfG')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\ProjectRequestor'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_ProjectRequestor, 'system\AccountLocked', getdate(), 'americas\lasta', getdate(),'CommentOfH')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\RestrictedAccess'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_RestrictedAccess, 'americas\lasta', getdate(), 'system\Manufacturing', getdate(),'CommentOfI')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\Everyone'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_Everyone, 'system\Everyone', getdate(),'system\DataAdmin', getdate(),'CommentOfJ')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\AccountLocked'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_AccountLocked, 'system\ProjectRequestor', getdate(), 'americas\lasta', getdate(),'CommentOfQ')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\TechnicalSupport'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_TechSupport, 'system\Manufacturing', getdate(), 'system\UserAdmin', getdate(),'CommentOfL')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\Manufacturing'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_Manufacturing, 'system\DataAdmin', getdate(), 'system\Administrator', getdate(),'CommentOfM')
		SELECT @personId = Id FROM [dbo].[Person] WHERE WindowsId = 'system\EnableOptionalFeatures'
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn],[Comment]) VALUES (@personId, @intRole_EnableOptionalFeatures, 'system\Administrator', getdate(), 'system\Everyone', getdate(),'CommentOfN')
	END

	PRINT 'Adding rows to [dbo].[Note]'
	BEGIN	
		SET IDENTITY_INSERT [dbo].[Note] ON
		INSERT INTO [dbo].[Note] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Comment],[EntityTypeId],[EntityId],[NoteTypeId]) VALUES  (1, N'NoteOfA', 'system\Administrator', '03-JAN-2009', 'americas\lasta','04-JAN-2009', @intRowStatus_Active, N'A_Comment',1,1,1)
		INSERT INTO [dbo].[Note] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Comment],[EntityTypeId],[EntityId],[NoteTypeId]) VALUES  (2, N'NoteOfB',  'americas\lasta', '02-JAN-2009', 'americas\mukaimur','02-JAN-2009', @intRowStatus_Inactive, N'B_EntityType',2,2,2)
		INSERT INTO [dbo].[Note] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Comment],[EntityTypeId],[EntityId],[NoteTypeId]) VALUES  (3, N'NoteOfC',  'americas\mukaimur', '01-JAN-2009', 'system\DataAdmin','01-JAN-2009', @intRowStatus_Deleted, N'EntityTypeC',3,3,3)
		INSERT INTO [dbo].[Note] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Comment],[EntityTypeId],[EntityId],[NoteTypeId]) VALUES  (4, N'NoteOfD', 'system\DataAdmin', '05-JAN-2009', 'americas\mukaimur','03-JAN-2009', @intRowStatus_Active, N'EntityTypeD',4,4,4)
		INSERT INTO [dbo].[Note] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Comment],[EntityTypeId],[EntityId],[NoteTypeId]) VALUES  (5, N'NoteOfE', 'system\Administrator', '04-JAN-2009', 'system\Administrator','05-JAN-2009', @intRowStatus_Inactive, N'EntityTypeE',5,5,5)
		INSERT INTO [dbo].[Note] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Comment],[EntityTypeId],[EntityId],[NoteTypeId]) VALUES  (6, N'Active.NoteStatus',  'system\UserAdmin', '04-JAN-2009', 'system\UserAdmin','02-JAN-2009', @intRowStatus_Active, N'Active EntityType',6,6,6)
		INSERT INTO [dbo].[Note] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Comment],[EntityTypeId],[EntityId],[NoteTypeId]) VALUES  (7, N'Inactive.NoteStatus',  'system\Manufacturing', '02-JAN-2009', 'system\AccountLocked','04-JAN-2009', @intRowStatus_Inactive, N'Inactive EntityType',7,7,7)
		INSERT INTO [dbo].[Note] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Comment],[EntityTypeId],[EntityId],[NoteTypeId]) VALUES  (8, N'Deleted.NoteStatus',   'system\AccountLocked', '01-JAN-2009', 'system\Manufacturing','03-JAN-2009', @intRowStatus_Deleted, N'Deleted EntityType',8,8,8)
		SET IDENTITY_INSERT [dbo].[Note] OFF
	END
	
	PRINT 'Adding rows to [dbo].[NoteType]'
	BEGIN
		SET IDENTITY_INSERT [dbo].[NoteType] ON
		--INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (0, N'None', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment], [RowStatusId]) VALUES (21, N'NoteTypeOfA', 'system\Administrator', '03-JAN-2009', 'americas\lasta','04-JAN-2009', N'CommentOfA', @intRowStatus_Active)
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment], [RowStatusId]) VALUES (22, N'NoteTypeOfB', 'americas\lasta', '02-JAN-2009', 'americas\mukaimur','02-JAN-2009', N'CommentOfB',@intRowStatus_Inactive)
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment], [RowStatusId]) VALUES (23, N'NoteTypeOfC', 'americas\mukaimur', '01-JAN-2009', 'system\DataAdmin','01-JAN-2009', N'CommentOfC', @intRowStatus_Deleted)
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment], [RowStatusId]) VALUES (24, N'NoteTypeOfD', 'system\DataAdmin', '05-JAN-2009', 'americas\mukaimur','03-JAN-2009', N'CommentOfD', @intRowStatus_Active)
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment], [RowStatusId]) VALUES (25, N'NoteTypeOfE', 'system\Administrator', '04-JAN-2009', 'system\Administrator','05-JAN-2009', N'CommentOfE',@intRowStatus_Inactive)
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment], [RowStatusId]) VALUES (26, N'Active.NoteTypeStatus', 'system\UserAdmin', '04-JAN-2009', 'system\UserAdmin','02-JAN-2009', N'CommentOfF', @intRowStatus_Active)
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment], [RowStatusId]) VALUES (27, N'Inactive.NoteTypeStatus','system\Manufacturing', '02-JAN-2009', 'system\AccountLocked','04-JAN-2009', N'CommentOfG',@intRowStatus_Inactive)
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment], [RowStatusId]) VALUES (28, N'Deleted.NoteTypeStatus', 'system\AccountLocked', '01-JAN-2009', 'system\Manufacturing','03-JAN-2009', N'CommentOfH', @intRowStatus_Deleted)
		SET IDENTITY_INSERT [dbo].[NoteType] OFF
	END
	
	PRINT 'Finished loading "Fetch Method Test" DB data'
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	---Capture the details of the original error
	DECLARE @ErrMsg nvarchar(4000), @ErrSeverity int
	SELECT	@ErrMsg = ERROR_MESSAGE(),
			@ErrSeverity = ERROR_SEVERITY()

	PRINT 'Error occurred while loading "Test" DB data'
	ROLLBACK TRANSACTION

	---Raise an error with the details of the original error
	RAISERROR(@ErrMsg, @ErrSeverity, 1)
END CATCH
GO

--- Reseed identities for each table
BEGIN
	PRINT 'Reseeding Identities'
	EXEC sp_MSForEachTable ' 
		IF OBJECTPROPERTY(object_id(''?''), ''TableHasIdentity'') = 1 
			BEGIN
				--DECLARE @highestId int
				--DECLARE @newSeed int
				--SET @highestId = (SELECT MAX([Id]) FROM ?);
				--SET @newSeed = (SELECT 1+ISNULL(@highestId, 0));
				--PRINT N''Reseeding ''''?'''' Identity to '' + CONVERT(NVARCHAR(20), @newSeed)
				--DBCC CHECKIDENT (''?'', RESEED, @newSeed) 
				PRINT N''Reseeding ''''?'''' Identity''
				DBCC CHECKIDENT (''?'', RESEED)
			END
	' 
END

GO
