-- =============================================
-- Author:	Robert Mukai
-- Author:	Justin Webster
-- Create date:	2008/07/01
-- Description:	Loads (i.e. inserts) the minimum set of data that is required to "bootstrap" the system and allow it to function.
-- Note:	Adapted from a script generated by Red Gat SQL Compare.
-- Note:	This script assumes that the DB is empty (i.e. has no table data).
-- Warning:	This script (as currently implemented) may reseed Identity columns in tables that are not otherwise modified by the script.
-- =============================================

SET NUMERIC_ROUNDABORT OFF
GO
SET XACT_ABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO

BEGIN TRY
	BEGIN TRANSACTION

	PRINT 'Loading "Bootstrap" DB data'

	DECLARE @strNewLine VARCHAR(2);
	DECLARE @dtDefaultValue_CreatedOn DATETIME;
	DECLARE @dtDefaultValue_ModifiedOn DATETIME;
	DECLARE @strDefaultValue_CreatedBy NVARCHAR(50);
	DECLARE @strDefaultValue_ModifiedBy NVARCHAR(50);
	DECLARE @intRowStatus_Active int;
	DECLARE @intRowStatus_Inactive int;
	DECLARE @intRowStatus_Deleted int;
	DECLARE @intRole_Administrator int;
	DECLARE @intRole_AccountLocked int;
	DECLARE @intRole_RestrictedAccess int;
	DECLARE @intRole_Everyone int;
	DECLARE @intRole_DataAdmin int;
	DECLARE @intRole_UserAdmin int;
	DECLARE @intRole_TechSupport int;
	DECLARE @intRole_Viewer int;
	DECLARE @intRole_Editor int;
	DECLARE @intRole_Validator int;
	DECLARE @intRole_Coordinator int;
	DECLARE @intPlatform_ITG int;
	DECLARE @intPlatform_Production int;
	DECLARE @intPlatform_Development int;
	
	SET @strNewLine = Char(13) + Char(10);
	SET @dtDefaultValue_CreatedOn = CONVERT(DATETIME, '20090101', 112);
	SET @dtDefaultValue_ModifiedOn = @dtDefaultValue_CreatedOn;
	SET @strDefaultValue_CreatedBy = N'system\system';
	SET @strDefaultValue_ModifiedBy = @strDefaultValue_CreatedBy;
	SET @intRowStatus_Active = 1;
	SET @intRowStatus_Inactive = 2;
	SET @intRowStatus_Deleted = 3;
	SET @intRole_Administrator = 1;
	SET @intRole_DataAdmin = 2;
	SET @intRole_UserAdmin = 3;
	SET @intRole_Viewer = 4;
	SET @intRole_Editor = 5;
	SET @intRole_Validator = 6;
	SET @intRole_Coordinator = 7;
	SET @intRole_AccountLocked = 8;
	SET @intRole_RestrictedAccess = 9;
	SET @intRole_Everyone = 10;
	SET @intRole_TechSupport = 11;

	PRINT 'Adding rows to [dbo].[RowStatus]'
	BEGIN
		SET IDENTITY_INSERT [dbo].[RowStatus] ON
		INSERT INTO [dbo].[RowStatus] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Description]) VALUES (1, N'Active', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'Regular data.')
		INSERT INTO [dbo].[RowStatus] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Description]) VALUES (2, N'Inactive', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'Obsolete or restricted data that should no longer be used, but that may still be referenced by existing data (e.g. for historical purposes).')
		INSERT INTO [dbo].[RowStatus] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Description]) VALUES (3, N'Deleted', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'Logically deleted data.')
		SET IDENTITY_INSERT [dbo].[RowStatus] OFF
	END

	PRINT 'Adding rows to [dbo].[EntityType]'
	BEGIN
		SET IDENTITY_INSERT [dbo].[EntityType] ON
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (1, N'Aardvark', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (2, N'Addendum', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (3, N'AddendumType', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (4, N'DDLChangeLog', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (5, N'EntityType', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (6, N'Log', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (7, N'Note', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (8, N'NoteType', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (9, N'Person', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (10, N'Person_Role', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (11, N'Role', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (12, N'RowStatus', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (13, N'Tag', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (14, N'Task', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (15, N'TaskType', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (16, N'ConfigurationServiceApplication', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (17, N'ConfigurationServiceGroup', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (18, N'ConfigurationServiceGroup_ConfigurationServiceLabelValue', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (19, N'ConfigurationServiceGroup_Tag', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (20, N'ConfigurationServiceGroupSelector', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (21, N'ConfigurationServiceGroupSelector_QueryParameterValue', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (22, N'ConfigurationServiceGroupStatus', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (23, N'ConfigurationServiceGroupType', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (24, N'ConfigurationServiceItem', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (25, N'ConfigurationServiceLabel', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (26, N'ConfigurationServiceLabelValue', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (27, N'ProxyURL', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (28, N'ProxyURL_QueryParameterValue', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (29, N'ProxyURL_Tag', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (30, N'ProxyURLDomain', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (31, N'ProxyURLGroupType', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (32, N'ProxyURLStatus', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (33, N'ProxyURLType', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (34, N'PublishTemp', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (35, N'QueryParameter', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (36, N'QueryParameter_ConfigurationServiceGroupType', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (37, N'QueryParameter_ProxyURLType', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (38, N'QueryParameterValue', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (39, N'JumpstationApplication', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (40, N'JumpstationGroup', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		--INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (41, N'JumpstationGroupJumpstationLabelValue', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (42, N'JumpstationGroupTag', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (43, N'JumpstationGroupSelector', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (44, N'JumpstationGroupSelectorQueryParameterValue', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (45, N'JumpstationGroupStatus', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (46, N'JumpstationGroupType', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (47, N'JumpstationMacro', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		--INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (39, N'', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		--INSERT INTO [dbo].[EntityType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (40, N'', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		SET IDENTITY_INSERT [dbo].[EntityType] OFF
	END

	PRINT 'Adding rows to [dbo].[NoteType]'
	BEGIN
		SET IDENTITY_INSERT [dbo].[NoteType] ON
		--INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (0, N'None', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (1, N'Debug', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (2, N'Info', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (3, N'Warning', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (4, N'Error', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (5, N'Milestone', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (6, N'State Change', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (7, N'Data Change', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (8, N'Data Change (Related Data)', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		--INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (9, N'State Change (Related Data)', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		--INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (10, N'Task Completed', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		--INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (11, N'Task Cancelled', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		--INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (12, N'Project Ended', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		--INSERT INTO [dbo].[NoteType] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [Comment]) VALUES (13, N'Notification(s) sent', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, N'')
		SET IDENTITY_INSERT [dbo].[NoteType] OFF
	END

	PRINT 'Adding rows to [dbo].[Role]'
	BEGIN
		SET IDENTITY_INSERT [dbo].[Role] ON
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_Administrator, N'Administrator', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, @intRowStatus_Active, N'Full administrators automatically possess all system roles (except limiting ones like Account Locked and Restricted Access). They are also the only role that can assign or remove the Administrator role.')
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_AccountLocked, N'Account Locked', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, @intRowStatus_Active, N'Users with locked accounts cannot access the SYSTEM at all, regardless of any other roles they may possess.')
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_RestrictedAccess, N'Restricted Access', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, @intRowStatus_Active, N'Restricted access users have limited access to (and limited capabilities within) the system, regardless of any other roles they possess (except Account Locked).')
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_Everyone, N'Everyone', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, @intRowStatus_Active, N'All users (except those who possess AccountLocked) automatically possesses this role.')
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_DataAdmin, N'Data Admin', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, @intRowStatus_Active, N'Data administrators are responsible for maintaining the system''s user-controlled configuration data and settings (but not the Operations or IT settings).')
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_UserAdmin, N'User Admin', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, @intRowStatus_Active, N'User administrators are responsible for maintaining the system''s user accounts, which includes the ability to assign or remove any user role (except the Administrator role).')
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_TechSupport, N'Technical Support', @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn, @intRowStatus_Active, N'Technical support users are responsible for troubleshooting and resolving system errors, user problem reports, and other such system maintainance activities.')
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_Viewer, N'Viewer', @strDefaultValue_CreatedBy, getdate(), @strDefaultValue_ModifiedBy, getdate(), @intRowStatus_Active, NULL)
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_Editor, N'Editor', @strDefaultValue_CreatedBy, getdate(), @strDefaultValue_ModifiedBy, getdate(), @intRowStatus_Active, NULL)
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_Validator, N'Validator', @strDefaultValue_CreatedBy, getdate(), @strDefaultValue_ModifiedBy, getdate(), @intRowStatus_Active, NULL)
		INSERT INTO [dbo].[Role] ([Id], [Name], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [RowStatusId], [Description]) VALUES (@intRole_Coordinator, N'Coordinator', @strDefaultValue_CreatedBy, getdate(), @strDefaultValue_ModifiedBy, getdate(), @intRowStatus_Active, NULL)
		SET IDENTITY_INSERT [dbo].[Role] OFF
	END

	PRINT 'Adding rows to [dbo].[Person]'
	BEGIN
		SET IDENTITY_INSERT [dbo].[Person] ON
		INSERT INTO [dbo].[Person] ([Id], [WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RowStatusId]) VALUES (1, N'system\system', N'ElementsCPS', null, N'ServiceAccount', N'ElementsCPS.Support@hp.com', @dtDefaultValue_CreatedOn, @strDefaultValue_CreatedBy, @dtDefaultValue_ModifiedOn, @strDefaultValue_ModifiedBy, @intRowStatus_Active)
		INSERT INTO [dbo].[Person] ([Id], [WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RowStatusId]) VALUES (2, N'americas\websterj', N'Justin', NULL, N'Webster', N'justin.webster@hp.com', @dtDefaultValue_CreatedOn, @strDefaultValue_CreatedBy, @dtDefaultValue_ModifiedOn, @strDefaultValue_ModifiedBy, @intRowStatus_Active)
		INSERT INTO [dbo].[Person] ([Id], [WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RowStatusId]) VALUES (3, N'americas\mukaimur', N'Robert', N'S', N'Mukai', N'robert.mukai@hp.com', @dtDefaultValue_CreatedOn, @strDefaultValue_CreatedBy, @dtDefaultValue_ModifiedOn, @strDefaultValue_ModifiedBy, @intRowStatus_Active)
		INSERT INTO [dbo].[Person] ([Id], [WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RowStatusId]) VALUES (4, N'americas\scott_trimber', N'Scott', N'L', N'Trimber', N'scott.trimber@hp.com', @dtDefaultValue_CreatedOn, @strDefaultValue_CreatedBy, @dtDefaultValue_ModifiedOn, @strDefaultValue_ModifiedBy, @intRowStatus_Active)
		INSERT INTO [dbo].[Person] ([Id], [WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RowStatusId]) VALUES (5, N'americas\bryantc', N'Cliff', N'', N'Bryant', N'cliff.bryant@hp.com', @dtDefaultValue_CreatedOn, @strDefaultValue_CreatedBy, @dtDefaultValue_ModifiedOn, @strDefaultValue_ModifiedBy, @intRowStatus_Active)
		
		INSERT INTO [dbo].[Person] ([Id], [WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RowStatusId]) VALUES (6, N'asiapacific\zling', N'Ling', N'', N'Zhang', N'zling@hp.com', @dtDefaultValue_CreatedOn, @strDefaultValue_CreatedBy, @dtDefaultValue_ModifiedOn, @strDefaultValue_ModifiedBy, @intRowStatus_Active)
		INSERT INTO [dbo].[Person] ([Id], [WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RowStatusId]) VALUES (8, N'asiapacific\wanling', N'Ling', N'', N'Wang', N'ling.wang3@hp.com', @dtDefaultValue_CreatedOn, @strDefaultValue_CreatedBy, @dtDefaultValue_ModifiedOn, @strDefaultValue_ModifiedBy, @intRowStatus_Active)
		INSERT INTO [dbo].[Person] ([Id], [WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RowStatusId]) VALUES (9, N'asiapacific\liujion', N'Liu_Jiong(Josh)', N'liu', N'liu', N'jiongl@hp.com', @dtDefaultValue_CreatedOn, @strDefaultValue_CreatedBy, @dtDefaultValue_ModifiedOn, @strDefaultValue_ModifiedBy, @intRowStatus_Active)
		INSERT INTO [dbo].[Person] ([Id], [WindowsId], [FirstName], [MiddleName], [LastName], [Email], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RowStatusId]) VALUES (12,N'asiapacific\yewe', N'Wei', null, N'Ye', N'we.ye@hp.com', @dtDefaultValue_CreatedOn, @strDefaultValue_CreatedBy, @dtDefaultValue_ModifiedOn, @strDefaultValue_ModifiedBy, @intRowStatus_Active)
	
		SET IDENTITY_INSERT [dbo].[Person] OFF
	END

	PRINT 'Adding rows to [dbo].[Person_Role]'
	BEGIN
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn]) VALUES (1, @intRole_Administrator, @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn)
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn]) VALUES (2, @intRole_Administrator, @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn)
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn]) VALUES (3, @intRole_Administrator, @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn)
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn]) VALUES (4, @intRole_Administrator, @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn)
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn]) VALUES (6, @intRole_Administrator, @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn)
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn]) VALUES (8, @intRole_Administrator, @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn)
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn]) VALUES (9, @intRole_Administrator, @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn)
		INSERT INTO [dbo].[Person_Role] ([PersonId], [RoleId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn]) VALUES (12, @intRole_Administrator, @strDefaultValue_CreatedBy, @dtDefaultValue_CreatedOn, @strDefaultValue_ModifiedBy, @dtDefaultValue_ModifiedOn)
	END

	PRINT 'Finished loading "Bootstrap" DB data'

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	---Capture the details of the original error
	DECLARE @ErrMsg nvarchar(4000), @ErrSeverity int
	SELECT	@ErrMsg = ERROR_MESSAGE(),
			@ErrSeverity = ERROR_SEVERITY()

	PRINT 'Error occurred while loading "Bootstrap" DB data'
	ROLLBACK TRANSACTION

	---Raise an error with the details of the original error
	RAISERROR(@ErrMsg, @ErrSeverity, 1)
END CATCH
GO

--- Reseed identities for each table
BEGIN
	PRINT 'Reseeding Identities'
	EXEC sp_MSForEachTable ' 
		IF OBJECTPROPERTY(object_id(''?''), ''TableHasIdentity'') = 1 
			BEGIN
				--DECLARE @highestId int
				--DECLARE @newSeed int
				--SET @highestId = (SELECT MAX([Id]) FROM ?);
				--SET @newSeed = (SELECT 1+ISNULL(@highestId, 0));
				--PRINT N''Reseeding ''''?'''' Identity to '' + CONVERT(NVARCHAR(20), @newSeed)
				--DBCC CHECKIDENT (''?'', RESEED, @newSeed) 
				PRINT N''Reseeding ''''?'''' Identity''
				DBCC CHECKIDENT (''?'', RESEED)
			END
	' 
END
GO
